# Generated by Django 4.2.23 on 2025-09-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cca2', models.CharField(max_length=2, unique=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('subregion', models.CharField(blank=True, max_length=100, null=True)),
                ('capital', models.CharField(blank=True, max_length=150, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('flag_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
